name: LetsGo
description: LetsGo

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  path: ^1.8.3

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.5
  fluttertoast: ^8.1.1
  uuid: ^4.2.0
  intl: ^0.18.1
  glassmorphism: ^3.0.0
  geocoding: ^2.0.5
  geolocator: ^10.1.0
  material_floating_search_bar: ^0.3.7
  booking_calendar: ^1.1.6
  custom_info_window: ^1.0.1
  badges: ^3.0.2
  page_transition: ^2.0.9
  flutter_svg: ^1.1.6
  provider: ^6.0.4
  icon_badge: ^1.0.0
  ticket_widget: ^1.0.2
  flutter_polyline_points: ^2.0.0
  custom_marker: ^1.0.0
  skeletons: ^0.0.3
  flutter_calendar_carousel: ^2.4.1
  shared_preferences: ^2.0.15
  flutter_stripe: 10.0.0
  flutter_material_pickers: ^3.3.0
  localstorage: ^4.0.0+1
  flutter_chat_ui: ^1.6.6
  open_filex: ^4.3.2
  mime: ^1.0.4
  calendar_timeline: ^1.0.5
  date_picker_timeline: ^1.2.3
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  http: ^1.0.0
  flutter_app_badger: ^1.5.0
  rxdart: ^0.27.4
  flutter_local_notifications: ^16.3.0
  socket_io_client: ^2.0.0
  expandable_text: ^2.3.0
  lottie: ^2.1.0
  expansion_tile_card: ^3.0.0
  flutter_pw_validator: ^1.5.0
  flutter_easyloading: ^3.0.5
  loading_animation_widget: ^1.2.0+4
  infinite_scroll_pagination: ^4.0.0
  animated_splash_screen: ^1.3.0
  animator: ^3.1.0
  cached_network_image: ^3.3.0
  overlay_support: ^2.1.0
  flutter_slidable: ^3.0.1
  smooth_page_indicator: ^1.1.0
  image_cropper: ^5.0.0
  image: ^4.1.3
  intl_phone_field: ^3.2.0
  file_picker: ^5.5.0
  plausible_analytics: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

flutter_icons:
  image_path: "assets/logo/LetsGo.png"
  #image_path_android: "assets/logo/logo.png"
  #image_path_ios: "assets/logo/logo.png"

  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/map/
    - assets/icons/
    - assets/icons/share.svg
    - assets/icons/heart.svg
    - assets/icons/comment.svg
    - assets/images/
    - assets/images/disc_icon.png
    - assets/images/photo-5.png
    - assets/ressources/
    - assets/community/
    - assets/logo/
    - assets/profil/
    - assets/lottie/loading.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
